
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 838840591105-lv9u8nsksisbjkkbjsqlmuj62vho7ohs.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          kakao:
            client-id: <your id>
            client-secret: <your secret>
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
          naver:
            client-id: _dudyQe0NT5vMiLMVBtU
            client-secret: Mn9dSNB_un
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
mybatis:
  mapper-locations:
    - /mappers/*.xml    
jwt:
  secret:  uAdzVUhnjML7pCLQLDapBdNacinrqdRjbaqLD7sMUfe0ILk8KKqk5Xb0WncSuIre   